#######################################################################
# Tutorial: https://www.youtube.com/watch?v=1A0GrK51cwY&list=PLaYEWfRap9wh5UZHBzMeYuEKGpK5-_-PJ&index=91
# Choco: https://chocolatey.org/install
# Packages: https://community.chocolatey.org/packages
#######################################################################

# Installiere Chocolatey
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

###################################

 Software installieren
choco install waterfox
choco upgrade waterfox
choco install python3
choco upgrade python3
choco install 7zip
choco upgrade 7zip
choco install adobereader
choco upgrade adobereader
choco install vscode
choco upgrade vscode
choco install vmware-workstation-player
choco upgrade vmware-workstation-player
choco install vlc
choco upgrade vlc
choco install jre8
choco upgrade jre8
choco install putty
choco upgrade putty
choco install ccleaner
choco upgrade ccleaner
choco install gimp
choco upgrade gimp
choco install atom
choco upgrade atom
choco install wireshark
choco upgrade wireshark
choco install octopusdeploy.tentacle
choco upgrade octopusdeploy.tentacle
choco install audacity
choco upgrade audacity
choco install eclipse
choco upgrade eclipse
choco install blender
choco upgrade blender
choco install github-desktop
choco upgrade github-desktop
choco install obs-studio
choco upgrade obs-studio
choco install epicgameslauncher
choco upgrade epicgameslauncher
choco install goggalaxy
choco upgrade goggalaxy
choco install steam-client
choco upgrade steam-client
choco install battle.net
choco upgrade battle.net
choco install teamspeak
choco upgrade teamspeak
choco install msiafterburner
choco upgrade msiafterburner
choco install xmind
choco upgrade xmind
choco install windowsrepair
choco upgrade windowsrepair
choco install streamlink
choco upgrade streamlink
choco install patch-my-pc
choco upgrade patch-my-pc
choco install glasswire
choco upgrade glasswire
choco install speedfan
choco upgrade speedfan
choco install win32diskimager
choco upgrade win32diskimager
choco install minecraft
choco upgrade minecraft
choco install atubecatcher
choco upgrade atubecatcher
choco install mediathekview
choco upgrade mediathekview
choco install furmark
choco upgrade furmark
choco install onlyoffice
choco upgrade onlyoffice
choco install ultraiso
choco upgrade ultraiso
choco install xmedia-recode
choco upgrade xmedia-recode
choco install lastactivityview
choco upgrade lastactivityview
choco install synfig
choco upgrade synfig
choco install lossless-cut
choco upgrade lossless-cut
choco install tv-browser
choco install systemninja
choco install xml-notepad
choco install notepadplusplus
